---
  ### ---------------------------------------------------------------------------
  ### APSTRA API AUTOMATION
  ### ---------------------------------------------------------------------------
  - hosts: localhost
    gather_facts: False
    connection: local
    roles:
      - { role: apstra_auth }

    tasks:
      - name: "Get Blueprint ID"
        ansible.builtin.uri:
          url: "{{ apstra.baseurl }}/blueprints"
          method: GET
         # return_content: yes
          status_code: 200
          headers:
            content-type: "application/json"
            AUTHTOKEN: "{{ login.json.token }}"
          validate_certs: false
          force_basic_auth: yes
        register: bp_ids


      - name: Retrieve Blueprint ID
        ansible.builtin.set_fact:
          bp_id: "{{ bp_ids.json | cleanup_bp_id(bp_name) }}"



      - name: Get virtual networks
        ansible.builtin.uri:
          url: "{{ apstra.baseurl }}/blueprints/{{ bp_id }}/nodes?node_type=virtual_network"
          method: GET
          return_content: yes
          status_code: 200
          headers:
            content-type: "application/json"
            AUTHTOKEN: "{{ login.json.token }}"
          validate_certs: false
          force_basic_auth: yes
          body_format: json
        register: vns



      - name: get vns
        ansible.builtin.set_fact:
          vn_id: "{{ item.value.id }}"
        when: item.value.label == vn_name
        loop: "{{ vns.json.nodes | dict2items }}"


      - name: show message body
        ansible.builtin.debug:
          msg: "{{ lookup('template','templates/delete_vn.j2') }}"

      - name: "Delete VN"
        ansible.builtin.uri:
          url: "{{ apstra.baseurl }}/blueprints/{{ bp_id }}/delete-virtual-networks"
          method: POST
          status_code: 201
          headers:
            content-type: "application/json"
            AUTHTOKEN: "{{ login.json.token }}"            
          validate_certs: false
          body: "{{ lookup('template','templates/delete_vn.j2') }}"
          force_basic_auth: yes
          body_format: json


        
        
        

